emit:
  - "@typespec/openapi3"
  - "@typespec/http-server-csharp"
options:
  "@typespec/openapi3":
     output-file: "../../output/openapi3.yaml"   
  "@typespec/http-server-csharp":
      emitter-output-dir: "{project-root}/../src/DiscDog.ApiService/Server"

