// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// <auto-generated />

using System;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace DiscDog.Service.Models
{

    public partial class Error
    {
        public object Code { get; set; }

        public string Message { get; set; }


    }
}
