// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// <auto-generated />

using System;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace DiscDog.Service.Models
{

    ///<summary>
    /// Resource create or update operation model.
    ///</summary>
    public partial class OwnerUpdate
    {
        public string Name { get; set; }

        public string Email { get; set; }

        public string UpdateBy { get; set; }


    }
}
