// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// <auto-generated />

using System;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace DiscDog.Service.Models
{

    ///<summary>
    /// Resource deleted successfully.
    ///</summary>
    public partial class ResourceDeletedResponse
    {

    }
}
