// <auto-generated/>
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace DiscDog.Client.Models
{
    /// <summary>
    /// Paged response of Dog items
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.17.0")]
    public partial class DogCollectionWithNextLink : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The link to the next page of items</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? NextLink { get; set; }
#nullable restore
#else
        public string NextLink { get; set; }
#endif
        /// <summary>The items on this page</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::DiscDog.Client.Models.Dog>? Value { get; set; }
#nullable restore
#else
        public List<global::DiscDog.Client.Models.Dog> Value { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::DiscDog.Client.Models.DogCollectionWithNextLink"/> and sets the default values.
        /// </summary>
        public DogCollectionWithNextLink()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::DiscDog.Client.Models.DogCollectionWithNextLink"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::DiscDog.Client.Models.DogCollectionWithNextLink CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            _ = parseNode ?? throw new ArgumentNullException(nameof(parseNode));
            return new global::DiscDog.Client.Models.DogCollectionWithNextLink();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "nextLink", n => { NextLink = n.GetStringValue(); } },
                { "value", n => { Value = n.GetCollectionOfObjectValues<global::DiscDog.Client.Models.Dog>(global::DiscDog.Client.Models.Dog.CreateFromDiscriminatorValue)?.AsList(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            _ = writer ?? throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("nextLink", NextLink);
            writer.WriteCollectionOfObjectValues<global::DiscDog.Client.Models.Dog>("value", Value);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
