// <auto-generated/>
using DiscDog.Client.Owner.Item;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace DiscDog.Client.Owner
{
    /// <summary>
    /// Builds and executes requests for operations under \owner
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.17.0")]
    public partial class OwnerRequestBuilder : BaseRequestBuilder
    {
        /// <summary>Gets an item from the DiscDog.Client.owner.item collection</summary>
        /// <param name="position">Unique identifier of the item</param>
        /// <returns>A <see cref="global::DiscDog.Client.Owner.Item.OwnerItemRequestBuilder"/></returns>
        public global::DiscDog.Client.Owner.Item.OwnerItemRequestBuilder this[string position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("id", position);
                return new global::DiscDog.Client.Owner.Item.OwnerItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::DiscDog.Client.Owner.OwnerRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public OwnerRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/owner", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::DiscDog.Client.Owner.OwnerRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public OwnerRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/owner", rawUrl)
        {
        }
    }
}
