// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// <auto-generated />

using System;
using System.Net;
using System.Threading.Tasks;
using System.Text.Json;
using System.Text.Json.Serialization;
using Microsoft.AspNetCore.Mvc;
using DiscDog.Service.Models;
using DiscDog.Service;

namespace DiscDog.Service.Controllers
{
    [ApiController]
    public abstract partial class DogResourcesControllerBase : ControllerBase
    {

        internal abstract IDogResources DogResourcesImpl { get; }

        ///<summary>
        /// Gets an instance of the resource.
        ///</summary>
        [HttpGet]
        [Route("/Dog/{id}")]
        [ProducesResponseType((int)HttpStatusCode.OK, Type = typeof(Dog))]
        public virtual async Task<IActionResult> Get(string id)
        {
            var result = await DogResourcesImpl.GetAsync(id);
            return Ok(result);
        }

        ///<summary>
        /// Updates an existing instance of the resource.
        ///</summary>
        [HttpPatch]
        [Route("/Dog/{id}")]
        [ProducesResponseType((int)HttpStatusCode.OK, Type = typeof(Dog))]
        public virtual async Task<IActionResult> Update(string id, DogUpdate body)
        {
            var result = await DogResourcesImpl.UpdateAsync(id, body);
            return Ok(result);
        }

        ///<summary>
        /// Deletes an existing instance of the resource.
        ///</summary>
        [HttpDelete]
        [Route("/Dog/{id}")]
        [ProducesResponseType((int)HttpStatusCode.OK, Type = typeof(void))]
        public virtual async Task<IActionResult> Delete(string id)
        {
            await DogResourcesImpl.DeleteAsync(id);
            return Ok();
        }

        ///<summary>
        /// Creates a new instance of the resource.
        ///</summary>
        [HttpPost]
        [Route("/Dog")]
        [ProducesResponseType((int)HttpStatusCode.OK, Type = typeof(Dog))]
        [ProducesResponseType((int)HttpStatusCode.Created, Type = typeof(Dog))]
        public virtual async Task<IActionResult> Create(DogCreate body)
        {
            var result = await DogResourcesImpl.CreateAsync(body);
            return Ok(result);
        }

        ///<summary>
        /// Lists all instances of the resource.
        ///</summary>
        [HttpGet]
        [Route("/Dog")]
        [ProducesResponseType((int)HttpStatusCode.OK, Type = typeof(DogCollectionWithNextLink))]
        public virtual async Task<IActionResult> List()
        {
            var result = await DogResourcesImpl.ListAsync();
            return Ok(result);
        }

    }
}
