// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// <auto-generated />

using System;
using System.Net;
using System.Threading.Tasks;
using System.Text.Json;
using System.Text.Json.Serialization;
using Microsoft.AspNetCore.Mvc;
using DiscDog.Service.Models;
using DiscDog.Service;

namespace DiscDog.Service.Controllers
{
    [ApiController]
    public abstract partial class OwnerResourcesControllerBase : ControllerBase
    {

        internal abstract IOwnerResources OwnerResourcesImpl { get; }

        ///<summary>
        /// Gets an instance of the resource.
        ///</summary>
        [HttpGet]
        [Route("/Owner/{id}")]
        [ProducesResponseType((int)HttpStatusCode.OK, Type = typeof(Owner))]
        public virtual async Task<IActionResult> Get(string id)
        {
            var result = await OwnerResourcesImpl.GetAsync(id);
            return Ok(result);
        }

        ///<summary>
        /// Updates an existing instance of the resource.
        ///</summary>
        [HttpPatch]
        [Route("/Owner/{id}")]
        [ProducesResponseType((int)HttpStatusCode.OK, Type = typeof(Owner))]
        public virtual async Task<IActionResult> Update(string id, OwnerUpdate body)
        {
            var result = await OwnerResourcesImpl.UpdateAsync(id, body);
            return Ok(result);
        }

        ///<summary>
        /// Deletes an existing instance of the resource.
        ///</summary>
        [HttpDelete]
        [Route("/Owner/{id}")]
        [ProducesResponseType((int)HttpStatusCode.OK, Type = typeof(void))]
        public virtual async Task<IActionResult> Delete(string id)
        {
            await OwnerResourcesImpl.DeleteAsync(id);
            return Ok();
        }

        ///<summary>
        /// Creates a new instance of the resource.
        ///</summary>
        [HttpPost]
        [Route("/Owner")]
        [ProducesResponseType((int)HttpStatusCode.OK, Type = typeof(Owner))]
        [ProducesResponseType((int)HttpStatusCode.Created, Type = typeof(Owner))]
        public virtual async Task<IActionResult> Create(OwnerCreate body)
        {
            var result = await OwnerResourcesImpl.CreateAsync(body);
            return Ok(result);
        }

        ///<summary>
        /// Lists all instances of the resource.
        ///</summary>
        [HttpGet]
        [Route("/Owner")]
        [ProducesResponseType((int)HttpStatusCode.OK, Type = typeof(OwnerCollectionWithNextLink))]
        public virtual async Task<IActionResult> List()
        {
            var result = await OwnerResourcesImpl.ListAsync();
            return Ok(result);
        }

    }
}
